// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Storage.EFCore;

namespace Storage.Migrations.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190428204327_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Schedule.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<long>("BuildingId")
                        .HasColumnName("building_id");

                    b.Property<string>("BuildingName")
                        .HasColumnName("building_name");

                    b.Property<int>("CabinetNumber")
                        .HasColumnName("cabinet_number");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnName("day_of_week");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("EndDay")
                        .HasColumnName("end_day");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_deleted")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnName("note");

                    b.Property<DateTime?>("StartDay")
                        .HasColumnName("start_day");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnName("start_time");

                    b.Property<string>("SubjectKindName")
                        .HasColumnName("subject_kind_name");

                    b.Property<string>("TeacherFirstname")
                        .HasColumnName("teacher_firstname");

                    b.Property<long?>("TeacherId")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TeacherLastname")
                        .HasColumnName("teacher_lastname");

                    b.Property<string>("TeacherMiddlename")
                        .HasColumnName("teacher_middlename");

                    b.Property<string>("TotalTime")
                        .HasColumnName("total_time");

                    b.Property<DateTime?>("Updated")
                        .HasColumnName("updated");

                    b.Property<int>("WeekType")
                        .HasColumnName("week_type");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("Id")
                        .HasName("ix_subjects_id");

                    b.HasIndex("IsDeleted")
                        .HasName("ix_subjects_is_deleted");

                    b.ToTable("subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
